---
title: "Simulation"
authors: "Or Duek & Guy Hazan"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: yes
---


Load libraries
```{r}
library(tidyverse)

library(ggplot2)

library(survey)



# library(magrittr)
# library(lubridate)
# library(stringr)
# library(tibble)
# library(broom)
# library(gt)
# library(knitr)
# library(devtools)
# library(DiagrammeR)
# library(parallel)
# library(foreach)
# library(tictoc)


```


```{r}
N = 1000000 # number of people
id <- 1:N
# build proportion of ages
(dat <- data.frame(min=c(15, 25, 35, 45, 55, 65), max=c(24, 34, 44, 54, 64, 100), prop=c(0.15, 0.134, 0.12, 0.1, 0.085,0.01)))
set.seed(144)  # For reproducibility
rows <- sample(nrow(dat), N, replace=TRUE, prob=dat$prop)
table(rows)
age <- round(dat$min[rows] + runif(N) * (dat$max[rows] - dat$min[rows]))
hist(age)
summary(age)

# gender
gender <- sample(c(0,1), N, replace = TRUE, prob = c(0.51, 0.49))
table(gender)

df <- tibble(id=id,age=age, gender=gender)

# generate age groups (for future use)
df$ageGroup <- cut(df$age, breaks=c(14,25,35,45,55,65,75,85,101), labels=c('<25','25-35','35-45','45-55','55-65','65-75','75-85','>85'))
```

Try something on my own

```{r}
# set r rate
r=1.12
x <- round(N - N/3) # number of subjects - remove half to keep enough way for the assignment
sick <- 0
sick_new <- c(10)
 
for (i in 1:50) {
  print(i)
  x_new = x - sick
  #beta = rbeta(1,1,20)
  if(x_new > sick_new[i]*r) {
  sick_new[i+1] <- sick_new[i] * r #rbinom(1, x_new, beta)
  # assign to people
  
  sick <- sick + sick_new[i+1]
  } else {
    print('no more')
  }
  
}
plot(sick_new)


```

# Divide Sick to demographics



## Generate proportion table

```{r}
ndf = round(N/5) # set number to sample from
# age has 8 groups
aUnit <- 28*2.13 # every decade (age)
ageProp <- 1 / aUnit ## 0.0023
# gender has two
sexProp <- 1 / 1.69
propT <- data.frame(ID=sample(ndf), Name=sample(ndf), 
    ageGroup=sample(c('<25','25-35','35-45','45-55','55-65','65-75','75-85','>85'), ndf, prob=c(ageProp, ageProp*2, ageProp*3, ageProp*4, ageProp*5, ageProp*6, ageProp*7, ageProp*8), replace=TRUE),
    gender=sample(c(1, 0), ndf, prob=c(sexProp, 1-sexProp), replace=TRUE))

ageSexInt <- interaction(propT$ageGroup, propT$gender)
props <- table(ageSexInt)/length(ageSexInt) # generate proportion table for sampling



```

## Generate data of sick

```{r}
# run first outside of loop to create dfNew
dfTest <- df
dNum <- sick_new[1] # numbe
nstrat <- as.vector(round(dNum*props))
names(nstrat) <- names(props)
nstrat[nstrat==0] <- 1 # need to solve - for now to avoid zeores
dfRows <- stratsample(interaction(df$ageGroup, df$gender), nstrat)
dfNew <-  dfTest[dfRows,]
dfNew$days = 1
dfTest <- dfTest[-dfRows,]

for (j in 2:40) {
  dNum <- sick_new[j] # numbe
  print(j)
  nstrat <- as.vector(round(dNum*props))
  names(nstrat) <- names(props)
  nstrat[nstrat==0] <- 1 
  dfRows <- stratsample(interaction(dfTest$ageGroup, dfTest$gender), nstrat)
  dfTemp <- dfTest[dfRows,]
  dfTemp$days = j
  dfNew <-  rbind(dfNew, dfTemp)
  
  dfTest <- dfTest[-dfRows,]

}
```

## Look at the data

```{r}
nrow(subset(dfNew,gender==1)) / nrow(subset(dfNew,gender==0)) # ratio if 1.686 as expected
hist(dfNew$days)
ggplot(dfNew, aes(x=days)) + geom_histogram() + facet_grid(~ageGroup) + theme_minimal()
```



```{r}
# df$days <- 101 # define number of days to get COVID
# dfMen <- subset(df,df$gender==1)
# dfWomen <- subset(df,df$gender==0)
# keepDatM <- tibble(id=1,  gender=1, days=50)
# keepDatF <- tibble(id=1, gender=0, days=50)
# 
# ageSexInt <- interaction(df$ageGroup, df$gender)
# 
# for (j in 1:30) {
#   dNum <- sick_new[j] # number of new sick people
#   gUnit <- 2.69 # male/female
#   aUnit <- 28*2.13 # every decade (age)
#   ageNum <- dNum/aUnit # get 
#   # define ages
#   age1 <- round(ageNum) # 15-25
#   age2 <- round(2 * ageNum) # 25 - 35
#   age3 <- round(3 * ageNum) # 35 - 45
#   age4 <- round(4 * ageNum) # 45 - 55
#   age5 <- round(5 * ageNum) # 55 - 65
#   age6 <- round(6 * ageNum) # 65 - 75
#   age7 <- round(7 * ageNum) # 75-85
#   age8 <- round(8 * ageNum) # 85-100
#  
#   # define genders
#   a <- dNum / gUnit
#   f <- round(a)
#  # print(f)
#   m <- round(1.69*a)
#  # print(m)
#  
#   
#   # check if enough people
#   if (m >= nrow(dfMen)) {
#     print('Stop Assignment at day')
#     print(j)
#     stop("Exhausted number of COVID patients", call. = FALSE)
#   } else {
#     
#   
#   maleInfected <- sample(nrow(dfMen), m) # sample index number of patients
#   femaleInfected <- sample(nrow(dfWomen), f) # sample index number of females
#   keepDatM <- rbind(keepDatM, tibble(id=maleInfected, gender=1,days=j))
#   keepDatF <- rbind(keepDatF, tibble(id=femaleInfected, gender=0,days=j))
#   
#   # remove those indexes from dataframes
#   dfMen <- dfMen[-maleInfected,]
#   dfWomen <- dfWomen[-femaleInfected,]
#   }}
# 
# dfBoth <- rbind(keepDatF, keepDatM)
# # remove the first line
# dfBoth = dfBoth[2:nrow(dfBoth),]
```



